"use client";
import { Button, Form, Input, List, Modal, Popconfirm, Tag } from "antd";
import { useState } from "react";
import type { Category, CategoryWritePayload } from "./finance.types";
export function CategoryManager({ categories, onCreate, onUpdate, onDelete }: { categories: Category[]; onCreate: (body: CategoryWritePayload) => void; onUpdate: (id: string, body: CategoryWritePayload) => void; onDelete: (id: string) => void }) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Category>(); const [form] = Form.useForm<CategoryWritePayload>();
  const submit = (values: CategoryWritePayload) => { if (editing) onUpdate(editing.id, values); else onCreate(values); setOpen(false); form.resetFields(); setEditing(undefined); };
  return <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Categories</h2><Button onClick={() => setOpen(true)}>Add category</Button></div><List bordered dataSource={categories} renderItem={(category) => <List.Item actions={[<Button key="edit" type="link" onClick={() => { setEditing(category); form.setFieldsValue({ name: category.name, icon: category.icon ?? undefined, color: category.color ?? undefined, budgetAmount: category.budgetAmount ?? undefined }); setOpen(true); }}>Edit</Button>, <Popconfirm key="delete" title="Delete category? Expenses must not reference it." onConfirm={() => onDelete(category.id)}><Button type="link" danger>Delete</Button></Popconfirm>]}><List.Item.Meta title={<span>{category.icon} {category.name} {category.color && <Tag color={category.color}>{category.color}</Tag>}</span>} description={category.budgetAmount != null ? `Budget ${category.budgetAmount}` : "No category budget configured"} /></List.Item>} /><Modal open={open} title={editing ? "Edit category" : "New category"} onCancel={() => setOpen(false)} footer={null}><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="name" label="Name" rules={[{ required: true }]}><Input maxLength={60} /></Form.Item><Form.Item name="icon" label="Icon"><Input maxLength={20} /></Form.Item><Form.Item name="color" label="Color"><Input placeholder="#2563eb" /></Form.Item><div className="flex justify-end"><Button type="primary" htmlType="submit">Save</Button></div></Form></Modal></section>;
}
